Adding CvTs
brain-score/vision pull request #1436
Opened 2024-11-05 16:03 UTC by LucyV4

Adds all of the CvTs from https://arxiv.org/abs/2103.15808 to the models and adds this paper as a reference to the new and existing CvTs

2024-11-05 17:42 UTC, KartikP commented
Looks like `cvt_cvt_w24_384_in22k_finetuned_in1k_4` ran out of memory. Going to open/close PR to retrigger unit test.

2024-11-05 19:16 UTC, LucyV4 commented
CvT W24 is already on brain score, so that one does not have to be runned necessarily. I only added the bibtex of the paper for that one. The CvT 13's and 21's are new

2024-11-05 19:28 UTC, KartikP requested changes
`cvt_cvt_21_384_in1k_4` and `cvt_cvt_13_384_in_1k_4` init files are swapped.

2024-11-05 19:28 UTC, KartikP commented on brainscore_vision/models/cvt_cvt_21_384_in1k_4/__init__.py
> +                            layers=get_layers('cvt_cvt-13-384-in1k_4'))
It appears that your `__init__.py` file for your `cvt_cvt_21_384_in1k_4` and `cvt_cvt_13_384_in_1k_4` are swapped and creating inconsistencies in the model_identifier for everything else in the respective directories.

Should be an easy fix and once that's done, I think this should pass.

2024-11-06 10:11 UTC, KartikP commented
`cvt_cvt-w24-384-in22k_finetuned-in1k_4` still causing out of memory issues. @LucyV4, could you remove the CVT W24 model from your PR. Then we can merge and score it.

2024-11-06 10:23 UTC, LucyV4 commented
Removed the bibtex from the W24 model

2024-11-06 12:27 UTC, LucyV4 commented
I see that the check failed because of my branch name, I think closing this and then making a new PR from the master branch of the fork is the best course of action?

2024-11-06 12:31 UTC, KartikP commented
@LucyV4 Hi Lucy, you're right but don't do anything just yet. There's one thing I want to clarify soon with the other developers regarding some private models that has the same model_identifiers (i.e., someone else has submitted the suite of CVT models) that is causing some issues. I'll get back to you today about what we'll do.

2024-11-06 12:34 UTC, LucyV4 commented
The private submission was me as well, I am writing a paper on vision models, illusions and brain scores. I found that the private submission had around 20 more tests and I did not want to upload all 6 models seperately

2024-11-06 13:29 UTC, KartikP commented
@LucyV4 To explain the situation at hand, earlier in the year, another user had submitted `cvt_cvt-{13,21}-{224,384}-in1k/{-in1k}` models. Essentially with the same identifiers as you did but they listed them as private. What this is now causing us is a conflict in our database with duplicate model_identifiers. Because this model is private, it also does not show up in the `models` directory.

In the future, we plan to have namespaces and keep all private models in the user-specific namespace, but we do not yet have this implemented.

For now, I'm going to ask you to append a unique identifier to each of your model identifiers. For example, `cvt_cvt-13-384-in1k_4` will become `cvt_cvt-13-384-in1k_4_lucyV4` or `keemink-lab_cvt_cvt-13-384-in1k_4`.

Once that's done, I'll let tests run again, and then merge this for you so you can get scores for your models.

2024-11-06 14:47 UTC, merged