Add cvt_cvt-w24-384-in22k_finetuned-in1k_4
brain-score/vision pull request #939
Opened 2024-06-25 02:50 UTC by pellegreene

2024-06-25 13:01 UTC, mike-ferguson requested changes
lgtm once the comments are addressed

2024-06-25 13:01 UTC, mike-ferguson commented on brainscore_vision/models/cvt_cvt-w24-384-in22k_finetuned-in1k_4/model.py
> +    # layers = []
Lines  37-40 can be uncommented out, and line 41 can be deleted. This must have been from an old version of that model that I was forcing it to use a certain layer. We can use all layers now.

2024-06-25 13:01 UTC, mike-ferguson commented on brainscore_vision/models/cvt_cvt-w24-384-in22k_finetuned-in1k_4/model.py
> +def get_model_list(name):
This method can be deleted (lines 14-18)

2024-07-01 14:31 UTC, mike-ferguson approved these changes

2024-07-01 19:38 UTC, deirdre-k commented on brainscore_vision/models/cvt_cvt_w24_384_in22k_finetuned_in1k_4/requirements.txt
> +PIL
@pellegreene PIL is no longer supported for Python 3 and instead has been replaced by [Pillow](https://pillow.readthedocs.io/en/stable/), same as https://github.com/brain-score/vision/pull/946

2024-07-03 13:45 UTC, mike-ferguson commented
god merged as Jenkins has been running (>12 hours)

2024-07-03 13:45 UTC, merged