Ep/add effnetb1 cutmixpatch sam robust32 avge6e8e9e10 manylayers 324x288
brain-score/vision pull request #947
Opened 2024-06-25 21:45 UTC by pellegreene

2024-07-01 14:22 UTC, mike-ferguson requested changes
Weights should be uploaded to S3, missing some packages in requirements.txt

2024-07-01 14:22 UTC, mike-ferguson commented on brainscore_vision/models/effnetb1_cutmixpatch_SAM_robust32_avge6e8e9e10_manylayers_324x288/requirements.txt
Also should include: 
torch
PIL
numpy

2024-07-01 14:22 UTC, mike-ferguson commented on brainscore_vision/models/effnetb1_cutmixpatch_SAM_robust32_avge6e8e9e10_manylayers_324x288/model.py
> +    model_tf_efficientnet_b1_ns.load_state_dict(torch.load(dir_path + "/tf_efficientnet_b1_ns_robust_cutmixpatchresize_SAM_e6e8e9e10.pth", map_location=torch.device('cpu'))["model"])
weights should be uploaded to S3

2024-07-03 13:30 UTC, pellegreene commented
@mike-ferguson Should be good to merge if it all looks good.

2024-07-03 13:35 UTC, merged