Ep/add effnetb1 cutmix augmix sam e1 5avg 424x377
brain-score/vision pull request #948
Opened 2024-06-25 21:45 UTC by pellegreene

2024-07-01 14:19 UTC, mike-ferguson requested changes
requirements.txt is blank

2024-07-01 14:19 UTC, mike-ferguson commented on brainscore_vision/models/effnetb1_cutmix_augmix_sam_e1_5avg_424x377/requirements.txt
I think this is empty by accident. Should have: 

`torch`
`PIL`
`numpy`
`timm`
`albumentations`

2024-07-03 03:32 UTC, pellegreene commented
Of note: Albumentations requires Python 3.8 or higher. As we are running on Python 3.7 for Travis and Jenkins the checks will not pass.

2024-07-03 13:30 UTC, pellegreene commented
@mike-ferguson Should be good to merge if all looks good

2024-07-03 13:33 UTC, mike-ferguson commented
God merged, see comment above regarding `albumentations`

2024-07-03 13:33 UTC, mike-ferguson approved these changes

2024-07-03 13:34 UTC, merged